### PR TITLE
Added sortParam method

### PR DESCRIPTION
**Pull request by Shimin-Zhang**
Hi Exeu, 

Sorry I'm quite new with the whole github thing (and programming in general), I edited a bit of the ECS class added an optional parameter function sortParam and changed the page function's validation since I think 10 is the maximum page number at the moment. I hope it's helpful with the library, if not feel free to ignore the pull request! 

john

### CODE REVIEW

**Comment by Exeu** [comment]
Hi,
thanks for your efforts.
Could you plese correct the Doc Block of the new function?
There has to be a Whitespace Character between the "*" and the Text like in the other functions above.

Thanks

**Comment by Exeu** [comment]
ping

**Comment by Exeu** [comment]
I will close now

**Comment by Shimin-Zhang** [comment]
Sorry about that Jan, I was thinking of adding a few more functions before fixing the comments. Anything else you think might be useful in particular?

**Comment by Exeu** [comment]
Hi,

actually i think there is nothing which should be implemented in this class.
The only thing i thought about is the limitation of the page parameter which you have set to 10.
In my opinion this check could be removed because if your are going to enter a higher number there will be no error or something else.
So if amazon decides to increase this value this class must not be touched again.

**Pull request closed without merging**
